services:
  - type: web
    name: anime-release-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python anime_release_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: ADMIN_USER_ID
        sync: false
